# .devcontainer/docker-compose.yml
version: '3.8'

services:
  weblate:
    image: weblate/weblate:5.10.4.0
    # Use the original entrypoint, but override the command to start with debugpy
    # listening on port 5678 and run the server without auto-reloading.
    # Note: /app/bin/start eventually calls 'weblate runserver ...'
    # We explicitly set the entrypoint to the python interpreter and pass
    # debugpy and runserver arguments via the command list.
    entrypoint: /app/venv/bin/python
    command: 
      - "-m"
      - "debugpy"
      - "--wait-for-client"
      - "--listen"
      - "0.0.0.0:5678"
      - "/app/manage.py" # Path to Django's manage.py inside the container
      - "runserver"
      - "0.0.0.0:8080"
      - "--noreload"
    restart: unless-stopped
    depends_on:
      - database
      - cache
    ports:
      # Expose Weblate web interface (adjust host port if 8080 is taken)
      - "8080:8080"
    volumes:
      # Mount the project root (containing your plugins) into /workspace
      # Note: '..' refers to the parent directory of .devcontainer, which is the project root.
      - ..:/workspace:cached
      # Persistent data volume for Weblate (optional, but recommended)
      - weblate-data:/app/data
      # Temporary storage (can use tmpfs for performance if needed)
      # - tmpfs:/app/cache
      # - tmpfs:/tmp
    environment:
      # --- Basic Weblate Settings ---
      WEBLATE_SITE_DOMAIN: localhost:8080 # Adjust if you use a different host port
      WEBLATE_ADMIN_NAME: Weblate Admin
      WEBLATE_ADMIN_EMAIL: admin@example.com # Change as needed
      WEBLATE_ADMIN_PASSWORD: admin # Change for security if needed
      WEBLATE_SERVER_EMAIL: weblate@example.com
      WEBLATE_DEFAULT_FROM_EMAIL: weblate@example.com
      WEBLATE_ALLOWED_HOSTS: '*' # Be more specific in production

      # --- Development Settings ---
      WEBLATE_DEBUG: 1
      WEBLATE_LOGLEVEL: DEBUG
      WEBLATE_REGISTRATION_OPEN: 1 # Allow easy registration during development

      # --- Plugin Settings ---
      # Tell Weblate where to find custom addons (mounted from your workspace)
      WEBLATE_ADDONS: /workspace/addons:/workspace/checks:/workspace/fixups # Add other plugin paths if needed

      # --- Service Connections ---
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432 # Default PostgreSQL port
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: weblate_password # Use a secure password
      POSTGRES_DB: weblate
      REDIS_HOST: cache
      REDIS_PORT: 6379 # Default Redis port
      # No need for DJANGO_SETTINGS_MODULE, the base image handles this

  database:
    image: postgres:16-alpine # Use a specific version
    restart: unless-stopped
    environment:
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: weblate_password # Must match WEBLATE service
      POSTGRES_DB: weblate
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Expose port only if direct access from host is needed for debugging
    # ports:
    #   - "5432:5432"

  cache:
    image: redis:7-alpine # Use a specific version
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  weblate-data:
  postgres-data:
  redis-data:
